# ---------------------------------------------------------------------------
#                   Automatic Announcing options
# ---------------------------------------------------------------------------
# Announce Premium on enter.
# Default = False
AnnouncePremiumLogin = false
# Choose the message for the ad Premium with clan member name
# Variables: %player%, %clan%
AnnouncePremiumLoginByClanMemberMsg = The Premium %player% clan member of %clan% is now online.
# Choose the message for the ad Premium without the clan member name
# Variables: %player%
AnnouncePremiumLoginByPlayerMsg = The Premium %player% is now online.

# Announce Hero Login only you stay in Base Class
# Default : False
AnnounceHero = True
# Variables: %player%, %clan%, %classe%
AnnounceHeroLoginByClanMemberMsg = The Hero %player% of %class% clan member %clan% is Online.
# Choose the message for the ad hero without the clan member name
# Variables: %player%, %classe%
AnnounceHeroLoginByPlayerMsg = The Hero %player% of the %classe% class is Online.

#============================================================
#                 Raid Grand Boss Messenge
#============================================================
# Announcement of raid bosses listed at spawn
AnnounceSpawnRaidBoss = True
AnnounceRaidBossId = 25299,25309,25302,25312,25305,25315,25450,25269

# Announce to Alive bosses.
AnnounceSpawnGranBoss = True

# Raid boss/ Grand boss defeated message
EnableBossDefeatedMsg = True
# Choose message for raid boss defeated by clan member
# Variables: %raidboss%, %player%, %clan%
RaidBossDefeatedByClanMemberMsg = Raid Boss %raidboss% was killed by: %player% of the clan: %clan%.
# Choose message for raid boss defeated by player
# Variables: %raidboss%, %player%
RaidBossDefeatedByPlayerMsg = Raid Boss %raidboss% was killed by: %player%.
# Choose message for grand boss defeated by clan member
# Variables: %grandboss%, %player%, %clan%
GrandBossDefeatedByClanMemberMsg = Grand Boss %grandboss% was killed by: %player% of the clan: %clan%.
# Choose message for grand boss defeated by player
# Variables: %grandboss%, %player%
GrandBossDefeatedByPlayerMsg = Grand Boss %grandboss% was killed by: %player%.

#============================================================
#                       FlagZone Messenge
#============================================================
#Messege to enter to Zona FlagZone
FlagZoneMessageTextEnter = You entered the Chaotic Zone!

#Time Show Messenge to player Entre to Zone
FlagZoneMessegeTimeEnter = 4

#Messege to enter to Zona FlagZone
FlagZoneMessageTextExit = You left the Chaotic Zone!

#Time Show Messenge to player Exit the Zone
FlagZoneMessegeTimeExit = 4

#============================================================
# Announcer PvP - Pk Kills
#============================================================
AnnounceKill = True
AnnouncePvpMsg = Player: $killer Hunter $target in 
AnnouncePkMsg = Player: $killer Ha assasined $target in 

